version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/http-srv
hooks:
  BeforeInstall:
    - location: before_install.sh
      timeout: 30
  AfterInstall:
    - location: after_install.sh
      timeout: 30
  ApplicationStart:
    - location: start.sh
      timeout: 30
  ApplicationStop:
    - location: stop.sh
      timeout: 30