version: 0.2
phases:
  install:
    runtime-versions: 
      dotnet: 8.0
  build:
    commands:
      - dotnet publish -c Release --self-contained=false --runtime linux-x64
artifacts:
  files:
    - scripts/*
    - appspec.yml
    - bin/Release/net8.0/linux-x64/*
  discard-paths: yes